# Generated by Django 5.2.8 on 2025-12-11 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название склада')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Марка/Модель')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Госномер')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('fuel_type', models.CharField(default='АИ-95', max_length=50, verbose_name='Тип топлива')),
                ('current_mileage', models.PositiveIntegerField(default=0, verbose_name='Текущий пробег (км)')),
                ('last_service_mileage', models.PositiveIntegerField(default=0, verbose_name='Пробег на последнем ТО')),
                ('checklist', models.TextField(blank=True, default='1. Проверь уровень масла\n2. Проверь уровень жидкостей\n3. Проверь наличие топливной карты', verbose_name='Чек-лист при выдаче')),
                ('insurance_expiry', models.DateField(blank=True, null=True, verbose_name='Дата окончания страховки')),
                ('is_truck', models.BooleanField(default=False, verbose_name='Это грузовой автомобиль')),
                ('last_ti_date', models.DateField(blank=True, null=True, verbose_name='Дата последнего Техосмотра')),
                ('status', models.CharField(choices=[('PARKED', 'На парковке'), ('ON_ROUTE', 'На выезде'), ('MAINTENANCE', 'На обслуживании (ТО)'), ('TECH_INSPECTION', 'На техосмотре'), ('BROKEN', 'СЛОМАН')], default='PARKED', max_length=20, verbose_name='Статус')),
                ('current_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_important', models.BooleanField(default=False, verbose_name='Важная новость (красная)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('article', models.CharField(max_length=50, verbose_name='Артикул')),
                ('item_type', models.CharField(choices=[('TOOL', 'Инструмент'), ('EQUIPMENT', 'Экипировка'), ('CONSUMABLE', 'Расходник')], max_length=20, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('minimum_stock', models.PositiveIntegerField(default=0, help_text='Если остаток на складах упадет ниже этого числа, появится уведомление. 0 = не отслеживать.', verbose_name='Минимальный остаток')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
                'unique_together': {('name', 'article')},
            },
        ),
        migrations.CreateModel(
            name='ToolKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название комплекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('IN_STOCK', 'На складе'), ('ISSUED', 'Выдан')], default='IN_STOCK', max_length=20, verbose_name='Статус')),
                ('co_workers', models.ManyToManyField(blank=True, related_name='working_kits', to=settings.AUTH_USER_MODEL, verbose_name='Со-работники')),
                ('current_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse', verbose_name='Место хранения')),
            ],
            options={
                'verbose_name': 'Комплект',
                'verbose_name_plural': 'Комплекты',
            },
        ),
        migrations.CreateModel(
            name='ToolInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.CharField(max_length=50, unique=True, verbose_name='Инвентарный номер')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('status', models.CharField(choices=[('IN_STOCK', 'В наличии'), ('ISSUED', 'Выдан'), ('BROKEN', 'В ремонте'), ('LOST', 'Утерян/Списан')], default='IN_STOCK', max_length=20, verbose_name='Статус')),
                ('condition', models.CharField(choices=[('NEW', 'Новое'), ('USED', 'Б/У'), ('BROKEN', 'Сломано')], default='NEW', max_length=20, verbose_name='Состояние')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='inventory.car', verbose_name='В машине')),
                ('current_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='У сотрудника')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.nomenclature', verbose_name='Что это')),
                ('kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='inventory.toolkit', verbose_name='В комплекте')),
                ('current_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse', verbose_name='На складе')),
            ],
            options={
                'verbose_name': 'Экземпляр инструмента',
                'verbose_name_plural': 'Инструменты (Учет)',
            },
        ),
        migrations.CreateModel(
            name='MovementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('action_type', models.CharField(choices=[('RECEIPT', 'Приемка'), ('ISSUE', 'Выдача'), ('RETURN', 'Возврат'), ('WRITEOFF', 'Списание'), ('KIT_ISSUE', 'Выдача Комплекта'), ('KIT_RETURN', 'Возврат Комплекта'), ('CAR_ISSUE', 'Выдача Авто'), ('CAR_RETURN', 'Возврат Авто'), ('CAR_TO_MAINT', 'Отправка на ТО'), ('CAR_FROM_MAINT', 'Возврат с ТО'), ('CAR_TO_TI', 'Отправка на Техосмотр'), ('CAR_FROM_TI', 'Возврат с Техосмотра')], max_length=20, verbose_name='Тип')),
                ('nomenclature_name', models.CharField(blank=True, max_length=200, verbose_name='Название (Архив)')),
                ('nomenclature_article', models.CharField(blank=True, max_length=50, verbose_name='Артикул (Архив)')),
                ('serial_number', models.CharField(blank=True, max_length=50, verbose_name='S/N (Архив)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('kit_name', models.CharField(blank=True, max_length=200, verbose_name='Комплект (Архив)')),
                ('car_name', models.CharField(blank=True, max_length=200, verbose_name='Авто (Архив)')),
                ('trip_mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег за поездку')),
                ('fuel_liters', models.PositiveIntegerField(blank=True, null=True, verbose_name='Заправлено (л)')),
                ('maintenance_work', models.TextField(blank=True, verbose_name='Работы')),
                ('composition', models.TextField(blank=True, verbose_name='Состав комплекта (Snapshot)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL)),
                ('source_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_tools', to='inventory.car')),
                ('source_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned', to=settings.AUTH_USER_MODEL)),
                ('target_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_tools', to='inventory.car')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received', to=settings.AUTH_USER_MODEL)),
                ('nomenclature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.nomenclature')),
                ('tool_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.toolinstance')),
                ('source_kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_tools', to='inventory.toolkit')),
                ('target_kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_tools', to='inventory.toolkit')),
                ('source_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing', to='inventory.warehouse')),
                ('target_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Запись в журнале',
                'verbose_name_plural': 'Журнал движений',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('allowed_warehouses', models.ManyToManyField(blank=True, to='inventory.warehouse', verbose_name='Доступные склады')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumableBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.nomenclature', verbose_name='Расходник')),
                ('kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='inventory.toolkit', verbose_name='В комплекте')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Остаток расходника',
                'verbose_name_plural': 'Расходники (Баланс)',
                'unique_together': {('nomenclature', 'holder', 'kit'), ('nomenclature', 'warehouse', 'kit')},
            },
        ),
    ]
