# Generated by Django 5.2.8 on 2025-11-20 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('article', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('item_type', models.CharField(choices=[('TOOL', 'Инструмент (штучный, инвентарный)'), ('CONSUMABLE', 'Расходник (количественный)')], max_length=20, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название склада')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='ToolInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.CharField(max_length=50, unique=True, verbose_name='Инвентарный номер')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('status', models.CharField(choices=[('IN_STOCK', 'В наличии'), ('ISSUED', 'Выдан'), ('BROKEN', 'В ремонте'), ('LOST', 'Утерян/Списан')], default='IN_STOCK', max_length=20, verbose_name='Статус')),
                ('current_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='У сотрудника')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.nomenclature', verbose_name='Что это')),
                ('current_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse', verbose_name='На складе')),
            ],
            options={
                'verbose_name': 'Экземпляр инструмента',
                'verbose_name_plural': 'Инструменты (Учет)',
            },
        ),
        migrations.CreateModel(
            name='MovementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('action_type', models.CharField(choices=[('RECEIPT', 'Приемка (Поступление)'), ('ISSUE', 'Выдача'), ('RETURN', 'Возврат'), ('WRITEOFF', 'Списание')], max_length=20, verbose_name='Тип операции')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество (для расходников)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий/Проект')),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='Кто оформил')),
                ('source_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned', to=settings.AUTH_USER_MODEL, verbose_name='От сотрудника')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received', to=settings.AUTH_USER_MODEL, verbose_name='Сотруднику')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.nomenclature', verbose_name='Товар')),
                ('tool_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.toolinstance', verbose_name='Конкретный инструмент')),
                ('source_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing', to='inventory.warehouse', verbose_name='Со склада')),
                ('target_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming', to='inventory.warehouse', verbose_name='На склад')),
            ],
            options={
                'verbose_name': 'Запись в журнале',
                'verbose_name_plural': 'Журнал движений',
            },
        ),
        migrations.CreateModel(
            name='ConsumableBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.nomenclature', verbose_name='Расходник')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Остаток расходника',
                'verbose_name_plural': 'Расходники (Баланс)',
                'unique_together': {('nomenclature', 'holder'), ('nomenclature', 'warehouse')},
            },
        ),
    ]
