# Generated by Django 5.2.8 on 2025-11-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolinstance',
            name='condition',
            field=models.CharField(choices=[('NEW', 'Новое'), ('USED', 'Б/У'), ('BROKEN', 'Сломано')], default='NEW', max_length=20, verbose_name='Состояние'),
        ),
    ]
