# Generated by Django 5.2.8 on 2025-11-21 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_toolinstance_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementlog',
            name='nomenclature_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (Архив)'),
        ),
        migrations.AlterField(
            model_name='movementlog',
            name='nomenclature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.nomenclature', verbose_name='Товар'),
        ),
    ]
