# Generated by Django 5.2.8 on 2025-11-21 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_movementlog_nomenclature_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movementlog',
            name='nomenclature_article',
            field=models.CharField(blank=True, max_length=50, verbose_name='Артикул (Архив)'),
        ),
        migrations.AddField(
            model_name='movementlog',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='S/N (Архив)'),
        ),
        migrations.AlterField(
            model_name='movementlog',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='movementlog',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='movementlog',
            name='source_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movementlog',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='movementlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movementlog',
            name='target_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming', to='inventory.warehouse'),
        ),
    ]
