# Generated by Django 5.2.8 on 2025-11-21 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_movementlog_nomenclature_article_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementlog',
            name='action_type',
            field=models.CharField(choices=[('RECEIPT', 'Приемка (Поступление)'), ('ISSUE', 'Выдача'), ('RETURN', 'Возврат'), ('WRITEOFF', 'Списание'), ('KIT_ISSUE', 'Выдача Комплекта'), ('KIT_RETURN', 'Возврат Комплекта')], max_length=20, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='movementlog',
            name='tool_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.toolinstance'),
        ),
        migrations.CreateModel(
            name='ToolKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название комплекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('IN_STOCK', 'На складе'), ('ISSUED', 'Выдан')], default='IN_STOCK', max_length=20, verbose_name='Статус')),
                ('current_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Комплект',
                'verbose_name_plural': 'Комплекты',
            },
        ),
        migrations.AddField(
            model_name='toolinstance',
            name='kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='inventory.toolkit', verbose_name='Входит в комплект'),
        ),
    ]
