# Generated by Django 5.2.8 on 2025-11-21 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_movementlog_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolkit',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse', verbose_name='Место хранения'),
        ),
    ]
