# Generated by Django 5.2.8 on 2025-11-22 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_toolkit_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementlog',
            name='kit_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Комплект (Архив)'),
        ),
        migrations.AddField(
            model_name='movementlog',
            name='source_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_tools', to='inventory.toolkit'),
        ),
        migrations.AddField(
            model_name='movementlog',
            name='target_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_tools', to='inventory.toolkit'),
        ),
    ]
