# Generated by Django 5.2.8 on 2025-11-22 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_movementlog_kit_name_movementlog_source_kit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movementlog',
            name='car_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Авто (Архив)'),
        ),
        migrations.AlterField(
            model_name='consumablebalance',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consumablebalance',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='movementlog',
            name='action_type',
            field=models.CharField(choices=[('RECEIPT', 'Приемка'), ('ISSUE', 'Выдача'), ('RETURN', 'Возврат'), ('WRITEOFF', 'Списание'), ('KIT_ISSUE', 'Выдача Комплекта'), ('KIT_RETURN', 'Возврат Комплекта'), ('CAR_ISSUE', 'Выдача Авто'), ('CAR_RETURN', 'Возврат Авто')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='movementlog',
            name='initiator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movementlog',
            name='nomenclature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.nomenclature'),
        ),
        migrations.AlterField(
            model_name='toolinstance',
            name='kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='inventory.toolkit', verbose_name='В комплекте'),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Марка/Модель')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Госномер')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('PARKED', 'На парковке'), ('ON_ROUTE', 'На выезде')], default='PARKED', max_length=20, verbose_name='Статус')),
                ('current_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.AddField(
            model_name='movementlog',
            name='source_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_tools', to='inventory.car'),
        ),
        migrations.AddField(
            model_name='movementlog',
            name='target_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_tools', to='inventory.car'),
        ),
        migrations.AddField(
            model_name='toolinstance',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='inventory.car', verbose_name='В машине'),
        ),
    ]
