# Generated by Django 5.2.8 on 2025-11-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_movementlog_car_name_alter_consumablebalance_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='checklist',
            field=models.TextField(blank=True, default='1. Проверь уровень масла\n2. Проверь уровень жидкостей\n3. Проверь наличие топливной карты', verbose_name='Чек-лист при выдаче'),
        ),
        migrations.AddField(
            model_name='car',
            name='current_mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='Текущий пробег (км)'),
        ),
        migrations.AddField(
            model_name='movementlog',
            name='fuel_liters',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Заправлено (л)'),
        ),
        migrations.AddField(
            model_name='movementlog',
            name='trip_mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег за поездку'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='item_type',
            field=models.CharField(choices=[('TOOL', 'Инструмент'), ('CONSUMABLE', 'Расходник')], max_length=20, verbose_name='Тип'),
        ),
    ]
