# Generated by Django 5.2.8 on 2025-11-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_car_checklist_car_current_mileage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания страховки'),
        ),
        migrations.AddField(
            model_name='movementlog',
            name='maintenance_work',
            field=models.TextField(blank=True, verbose_name='Работы по ТО'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('PARKED', 'На парковке'), ('ON_ROUTE', 'На выезде'), ('MAINTENANCE', 'На обслуживании')], default='PARKED', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='movementlog',
            name='action_type',
            field=models.CharField(choices=[('RECEIPT', 'Приемка'), ('ISSUE', 'Выдача'), ('RETURN', 'Возврат'), ('WRITEOFF', 'Списание'), ('KIT_ISSUE', 'Выдача Комплекта'), ('KIT_RETURN', 'Возврат Комплекта'), ('CAR_ISSUE', 'Выдача Авто'), ('CAR_RETURN', 'Возврат Авто'), ('CAR_TO_MAINT', 'Отправка на ТО'), ('CAR_FROM_MAINT', 'Возврат с ТО')], max_length=20, verbose_name='Тип'),
        ),
    ]
