# Generated by Django 5.2.8 on 2025-11-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_car_insurance_expiry_movementlog_maintenance_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='last_service_mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='Пробег на последнем ТО'),
        ),
    ]
