# Generated by Django 5.2.8 on 2025-11-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_car_last_service_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_truck',
            field=models.BooleanField(default=False, verbose_name='Это грузовой автомобиль'),
        ),
        migrations.AddField(
            model_name='car',
            name='last_ti_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего Техосмотра'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('PARKED', 'На парковке'), ('ON_ROUTE', 'На выезде'), ('MAINTENANCE', 'На обслуживании (ТО)'), ('TECH_INSPECTION', 'На техосмотре')], default='PARKED', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='movementlog',
            name='action_type',
            field=models.CharField(choices=[('RECEIPT', 'Приемка'), ('ISSUE', 'Выдача'), ('RETURN', 'Возврат'), ('WRITEOFF', 'Списание'), ('KIT_ISSUE', 'Выдача Комплекта'), ('KIT_RETURN', 'Возврат Комплекта'), ('CAR_ISSUE', 'Выдача Авто'), ('CAR_RETURN', 'Возврат Авто'), ('CAR_TO_MAINT', 'Отправка на ТО'), ('CAR_FROM_MAINT', 'Возврат с ТО'), ('CAR_TO_TI', 'Отправка на Техосмотр'), ('CAR_FROM_TI', 'Возврат с Техосмотра')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='movementlog',
            name='maintenance_work',
            field=models.TextField(blank=True, verbose_name='Работы'),
        ),
    ]
