# Generated by Django 5.2.8 on 2025-11-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_car_is_truck_car_last_ti_date_alter_car_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('AI-92', 'АИ-92'), ('AI-95', 'АИ-95'), ('AI-98', 'АИ-98'), ('DIESEL', 'Дизель (ДТ)'), ('GAS', 'Газ'), ('ELECTRIC', 'Электричество')], default='AI-95', max_length=20, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('PARKED', 'На парковке'), ('ON_ROUTE', 'На выезде'), ('MAINTENANCE', 'На обслуживании (ТО)'), ('TECH_INSPECTION', 'На техосмотре'), ('BROKEN', 'СЛОМАН')], default='PARKED', max_length=20, verbose_name='Статус'),
        ),
    ]
