# Generated by Django 5.2.8 on 2025-11-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_car_fuel_type_alter_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='АИ-95', max_length=50, verbose_name='Тип топлива'),
        ),
    ]
