# Generated by Django 5.2.8 on 2025-11-23 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_car_fuel_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consumablebalance',
            unique_together={('nomenclature', 'holder'), ('nomenclature', 'warehouse')},
        ),
        migrations.AddField(
            model_name='consumablebalance',
            name='kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='inventory.toolkit', verbose_name='В комплекте'),
        ),
        migrations.AlterUniqueTogether(
            name='consumablebalance',
            unique_together={('nomenclature', 'holder'), ('nomenclature', 'kit'), ('nomenclature', 'warehouse')},
        ),
    ]
