# Generated by Django 5.2.8 on 2025-11-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=0, help_text='Если остаток на складах упадет ниже этого числа, появится уведомление. 0 = не отслеживать.', verbose_name='Минимальный остаток'),
        ),
    ]
