# Generated by Django 5.2.8 on 2025-11-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_nomenclature_minimum_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementlog',
            name='composition',
            field=models.TextField(blank=True, verbose_name='Состав комплекта (Snapshot)'),
        ),
    ]
