# Generated by Django 5.2.8 on 2025-11-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_movementlog_composition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='article',
            field=models.CharField(max_length=50, verbose_name='Артикул'),
        ),
        migrations.AlterUniqueTogether(
            name='nomenclature',
            unique_together={('name', 'article')},
        ),
    ]
