# Generated by Django 5.2.8 on 2025-11-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_nomenclature_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='item_type',
            field=models.CharField(choices=[('TOOL', 'Инструмент'), ('EQUIPMENT', 'Экипировка'), ('CONSUMABLE', 'Расходник')], max_length=20, verbose_name='Тип'),
        ),
    ]
