# Generated by Django 5.2.8 on 2025-11-29 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_nomenclature_item_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='toolkit',
            name='co_workers',
            field=models.ManyToManyField(blank=True, related_name='working_kits', to=settings.AUTH_USER_MODEL, verbose_name='Со-работники'),
        ),
        migrations.AlterField(
            model_name='toolkit',
            name='current_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
    ]
