# Generated by Django 5.2.8 on 2025-11-29 13:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_toolkit_co_workers_alter_toolkit_current_holder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consumablebalance',
            unique_together={('nomenclature', 'holder', 'kit'), ('nomenclature', 'warehouse', 'kit')},
        ),
    ]
