# Generated by Django 5.2.8 on 2025-12-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_consumablebalance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementlog',
            name='action_type',
            field=models.CharField(choices=[('RECEIPT', 'Приемка'), ('ISSUE', 'Выдача'), ('RETURN', 'Возврат'), ('WRITEOFF', 'Списание'), ('KIT_ISSUE', 'Выдача Комплекта'), ('KIT_RETURN', 'Возврат Комплекта'), ('CAR_ISSUE', 'Выдача Авто'), ('CAR_RETURN', 'Возврат Авто'), ('CAR_TO_MAINT', 'Отправка на ТО'), ('CAR_FROM_MAINT', 'Возврат с ТО'), ('CAR_TO_TI', 'Отправка на Техосмотр'), ('CAR_FROM_TI', 'Возврат с Техосмотра'), ('KIT_EDIT', 'Редактирование комплекта')], max_length=20, verbose_name='Тип'),
        ),
    ]
